name: ci

on:
  pull_request:
    branches: [main]

jobs:  
  style:
    name: Style
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with: ${{ matrix.node-version }}
      - run: npm ci
      - run: next lint